name: Despliegue de Release (CD)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  llamar-plantilla:
    uses: carlcuevas/techmaster-central-devops/.github/workflows/plantilla-docker.yml@main
    with:
      publicar_imagen: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
