name: Validacion Continua (CI)

on:
  push:
    branches:
      - 'feature/*'

jobs:
  llamar-plantilla:
    uses: carlcuevas/techmaster-central-devops/.github/workflows/plantilla-docker.yml@main
    with:
      publicar_imagen: false
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
